### ISSUE TITLE
Crash clients

### ISSUE THREAD

**Issue by Scrik** [nilzao/soapbox-race#1]
After joining of the second player (player 2), input of a nickname and pressing "Next" has taken off from already entered player (player 1) for the world (The client was closed,crash) and also the client was closed at second (player 2). It was connected on a local network

http://pastebin.com/4suSVbdw

P.S: I have written the report that you knew

**Comment by Scrik** [comment]
Solved: Add email and password for userid 2 and 3

**Comment by nilzao** [comment]
you can add more users, i will update the readme about the user table.
