### ISSUE TITLE
Where is soapbox.exe?

### ISSUE THREAD

**Issue by FetchLeo** [nilzao/soapbox-race#11]
The README file mentions running a `soapbox.exe` file when you get your user ID and login token. Where is `soapbox.exe`?

Also, if you wouldn't mind giving some advice to someone who's trying to make their own server: Do you pass a user ID and login token to `nfsw.exe` along with the IP address of the server? I can't imagine any other way it would be done.

**Comment by nilzao** [comment]
soapbox.exe is a mod version of nfsw.exe, made by hackers, and it's somewhere over the internet, I cant host or point where it is.... github rules.

to pass Id and login token to nfsw.exe you can:
- create a shortcut in windows with parameters
- call in command line witn powershell or cmd

**Comment by FetchLeo** [comment]
@nilzao Alright thanks.
