### ISSUE TITLE
Start lobby

### ISSUE THREAD

**Issue by Scrik** [nilzao/soapbox-race#12]
I have started the race and udp server on one computer, also from this computer I have come into game and I have created a lobby. The second player doesn't see a lobby (There is an eternal search of players)
Computers are connected to the help of local WIFI
Sorry for my English
What I not correctly do?
PS: IP are entered two times in a line of start of the "soapbox-race" server
PSS: On VDS the same problem at me. Database everywhere MySQL

**Comment by nilzao** [comment]
some points:
you have 3 servers
- 1 http + 1 xmpp inside soapbox-race.jar
- 1 udp inside soapbox-race-udp.jar
  run all in one computer, don't need to run in both computers.

more things:
- you need to test powerups before try enter lobby, if not working, client need the "magical soapbox.exe version ;) "
- only button multiplayer in game works. The private match and global find races don't work.
- both players need to click multiplayer button of the same race, in less than 45 seconds from lobby created.
