### ISSUE TITLE
cloud you can provide soapbox.exe link?

### ISSUE THREAD

**Issue by Mellowz** [nilzao/soapbox-race#13]
i try to find on google but it's doesn't exists, can you upload for us ?

**Comment by FetchLeo** [comment]
@Mellowz See this: https://github.com/nilzao/soapbox-race/issues/11

Apparently Nilzao isn't allowed to share it here. GitHub terms I think.

**Comment by nilzao** [comment]
I heard about a forum...

http://www.elitepvpers.com/forum/need-speed-world/

ppl talking about soapbox.exe there.
