### ISSUE TITLE
why udp server show invalid hello packet!

### ISSUE THREAD

**Issue by Mellowz** [nilzao/soapbox-race#14]
> Generic udp server
> 
> to change port and protocol run:
> java -jar soapbox-udp.jar PORT FULL_PROTOCOL_CLASS_NAME
> 
> Example:
>  java -jar soapbox-udp.jar 1234 br.com.xht.udp.protocol.string.StringProtocol
> 
> listening on port: [9999]
> with protocol: [br.com.xht.udp.protocol.string.StringProtocol]
> 
> invalid hello packet!
> invalid hello packet!
> invalid hello packet!

**Comment by nilzao** [comment]
soapbox-race-udp is other project, not here, take a look inside README file, if you use StringProtocol, need to talk with udp server with Strings, not game.
