### ISSUE TITLE
[Bug] "Switch Drivers" causes game to crash due to a 500 error

### ISSUE THREAD

**Issue by FetchLeo** [nilzao/soapbox-race#16]
When using the server, trying to use the "Switch Drivers" button in NFS:W makes the game crash immediately, saying there was a 500 error. Based on some investigating I did, it seems like a 500 error is occurring when the `carslots` URL is called for a persona. When I go to it in the browser, I get a 500 error as well. However, no error response is returned so my browser displays a default page.

Any clue why this is happening? I'm sorry I can't provide more details; I don't do this very often.
Hopefully it's a simple fix. I'm not sure if this is even happening with other people, but I don't see why it wouldn't.

**Comment by berkay2578** [comment]
Server prints out the exception's stacktrace when a 500 is returned. If you have bought TH/Cop/SoundFX cars before the latest commit, then the issue is in the SkillModSlotCount located in the CUSTOMCAR table. Replace 5s with 6 and see if it helps.

**Comment by FetchLeo** [comment]
@berkay2578 Well, the problem is, it didn't print out a stacktrace at all. I'll try that, though.
