### ISSUE TITLE
[Connection-Bug] De-Sync and and and.. :/

### ISSUE THREAD

**Issue by EyJesstenEy** [nilzao/soapbox-race#20]
**Issues:**
De-Sync (1 Mins)
I cant see each other.
Add a Friends dont work.
I cant / now how to change the Port or IPv4

**Tryed to fix it:** 
Runed anything with Admin.
Deactivated my Firewall and Anti-Virus
Tryed to change the Ports to the 9998 or 1337

Plz help me :/

**Comment by EyJesstenEy** [comment]
Okay, now i fixed it that i can join each other. but when the game starts the start timers are de-sync and when it finaly starts a network error comes: NETERROR_HANDSHAKE_TIMEOUT

**Comment by nilzao** [comment]
this problem is inside another project:
https://github.com/nilzao/soapbox-race-udp
