### ISSUE TITLE
Failing to start

### ISSUE THREAD

**Issue by DI3HARD139** [nilzao/soapbox-race#21]
Java reports "no main manifest attribute, in soapbox-race-1.0.1-SNAPSHOT.jar"

OS: Ubuntu Server 16.04.1 x64

**Comment by nilzao** [comment]
first lines of REAME.md say to compile with maven using:
maven clean compile assembly:single

generating the file soapbox-race-1.0.1-SNAPSHOT-jar-with-dependencies.jar

maven clean verify, clean install will fail generating the file soapbox-race-1.0.1-SNAPSHOT.jar

**Comment by DI3HARD139** [comment]
I was able to successfully compile it via cmd prompt. Once launching the .jar on a linux server it just freezes at the following (see below). I get the feeling that it has something to do with an improper soapbox.properties file. I have manually loaded the .sql files found in the db folder into mySQL and the database exists.

[main] INFO org.eclipse.jetty.util.log - Logging initialized @92ms
Jan 17, 2017 10:06:30 AM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Sending client request on thread main
1 > POST http://127.0.0.1:9090/plugins/restapi/v1/users
1 > Authorization: y0gs2EUWSakiz1q5
1 > Content-Type: application/xml

Jan 17, 2017 10:06:30 AM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Client response received on thread main
1 < 401
1 < Access-Control-Allow-Credentials: true
1 < Access-Control-Allow-Headers: origin, content-type, accept, authorization
1 < Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
1 < Access-Control-Allow-Origin: *
1 < Content-Length: 0
1 < Date: Tue, 17 Jan 2017 09:06:30 GMT
1 < Expires: Thu, 01 Jan 1970 00:00:00 GMT
1 < Set-Cookie: JSESSIONID=c7s80k0kvg4u1fivswcz11zhl;Path=/;HttpOnly
1 < X-Frame-Options: same

Attempting to connect OpenFire XMPP Host. #1
Connected to OpenFire XMPP Host...
C->S [<?xml version='1.0' ?><stream:stream to='127.0.0.1' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>]
S->C [<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="198.245.49.229" id="9sz03h41al" xml:lang="en" version="1.0"><stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>EXTERNAL</mechanism><mechanism>CRAM-MD5</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms></stream:features>]
C->S [<starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'/>]
S->C [<proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/>]
C->S [<?xml version='1.0' ?><stream:stream to='127.0.0.1' xmlns='jabber:client' xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>]
C->S [<iq id='EA-Chat-1' type='get'><query xmlns='jabber:iq:auth'><username>nfsw.engine.engine</username></query></iq>]
S->C [<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="198.245.49.229" id="9sz03h41al" xml:lang="en" version="1.0"><stream:features><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>EXTERNAL</mechanism><mechanism>CRAM-MD5</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms></stream:features>]
C->S [<iq xml:lang='en' id='EA-Chat-2' type='set'><query xmlns='jabber:iq:auth'><username>nfsw.engine.engine</username><password>1234567890123456</password><resource>EA_Chat</resource><clientlock xmlns='http://www.jabber.com/schemas/clientlocking.xsd' id='900'>57b8914527daff651df93557aef0387e5aa60fae</clientlock></query></iq>]

**Comment by nilzao** [comment]
To use openfire server, you need to follow openfire/README.md instructions.

Or you can try the embedded version, changing soapbox.properties file:

from:
xmppServerType=OpenFire
#xmppServerType=Offline

to:
#xmppServerType=OpenFire
xmppServerType=Offline

**Comment by DI3HARD139** [comment]
I'll try it the 2nd way as for some reason. Despite reinstalling/compiling/configuring twice it still wouldn't take.

Thanks for the assistance :)

**Comment by DI3HARD139** [comment]
That worked! One last question. Where can I edit the Connection info for the SQL database? I have a password set for root@localhost.

Thanks again!

**Comment by nilzao** [comment]
edit the persistence.xml file.

can edit before building, or edit inside the jar (jar is a zip file)

**Comment by DI3HARD139** [comment]
Ok thanks

**Comment by DI3HARD139** [comment]
Ok so I fixed the issues with openfire. Latest troubles is it spams the terminal with nothing but "S->C []" after connecting.

Output:

`[main]` INFO org.eclipse.jetty.util.log - Logging initialized @84ms
Jan 26, 2017 7:41:34 AM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Sending client request on thread main
1 > POST http://127.0.0.1:9090/plugins/restapi/v1/users
1 > Authorization: <blanked>
1 > Content-Type: application/xml

Jan 26, 2017 7:41:34 AM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Client response received on thread main
1 < 500
1 < Content-Length: 0
1 < Date: Thu, 26 Jan 2017 06:41:34 GMT
1 < Expires: Thu, 01 Jan 1970 00:00:00 GMT
1 < Set-Cookie: JSESSIONID=13e50h8meiwt4q0enu2umfzx2;Path=/;HttpOnly
1 < X-Frame-Options: same

Attempting to connect OpenFire XMPP Host. #1
Connected to OpenFire XMPP Host...
C->S [<?xml version='1.0' ?><stream:stream to='127.0.0.1' xmlns='jabber:client'
 xmlns:stream='http://etherx.jabber.org/streams' version='1.0' xml:lang='en'>]
S->C [<?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" 
xmlns="jabber:client" from="198.245.49.229" id="3yql2j5hdt" xml:lang="en" version="1.0">]
S->C [<stream:error xmlns:stream="http://etherx.jabber.org/streams"><internal-server-error 
 `xmlns="urn:ietf:params:xml:ns:xmpp-streams"/></stream:error>]`

**Comment by nilzao** [comment]
you need to follow the openfire readme, same version, replace the cracked class file, and all configurations.
