### ISSUE TITLE
[question] will this be updated ?

### ISSUE THREAD

**Issue by tomekb530** [nilzao/soapbox-race#23]
I know you're busy or something but will soapbox project be updated ?

**Comment by vaporwavie** [comment]
@Fabsko sent a PR a few weeks ago, so I think this is probably a yes... Nevertheless, @nilzao's last commit was on (sigh) **August** :(

**Comment by nilzao** [comment]
Project will move to here https://github.com/SoapBoxRaceWorld when patreon campaign start.
